In [1]:
#wap a program to print a numpy array...using python list, display the array and print the shape and datatype of array

import numpy as np

list = [10, 20, 30, 40, 50]
arr = np.array(list)

print(arr)
print(arr.shape)
print("Data Type:" ,arr.dtype)

[10 20 30 40 50]
(5,)
Data Type: int64


In [2]:

import numpy as np

matrix1 = np.ones((2, 5))

print("Matrix:", matrix1)
print(matrix1.shape)


Matrix: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(2, 5)


In [3]:
array = np.arange(1, 13)
reshaped_arr = array.reshape(3, 4)

print("Original Array:", array)
print("Original Shape:", array.shape)

print("Reshaped Array:", reshaped_arr)
print("Reshaped Shape:", reshaped_arr.shape)

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Shape: (12,)
Reshaped Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped Shape: (3, 4)


In [4]:
import numpy as np
array1= np.random.randint(1,100,10)
print(array1)
print("Minimum:", array1.min())
print("Maximum:", array1.max())
print("Mean:", array1.mean())
print("Sum:", array1.sum())

[ 7 46 42 49 76 92 70 35 80 21]
Minimum: 7
Maximum: 92
Mean: 51.8
Sum: 518


In [5]:
import pandas as pd

data = {
    "Student_Name": ["Alice", "Bob", "Charlie", "David"],
    "Marks": [85, 90, 78, 92]
}

df = pd.DataFrame(data)

print("DataFrame:", df)
print(df.dtypes)

DataFrame:   Student_Name  Marks
0        Alice     85
1          Bob     90
2      Charlie     78
3        David     92
Student_Name    object
Marks            int64
dtype: object


In [8]:
import pandas as pd

df = pd.read_csv("/content/Iris.csv")

print(df.head())
print(df.iloc[-5:, -5:])

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica


In [10]:
import pandas as pd
df = pd.read_csv("/content/Iris.csv")

print("Number of Rows:", df.shape[0])

print("\nMissing Values in Each Column:")
print(df.isnull().sum())

Number of Rows: 150

Missing Values in Each Column:
Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64


In [11]:
import pandas as pd
df = pd.read_csv("/content/Iris.csv")
print("DataFrame:\n", df)
print("\nStatistical Summary:\n")
print(df.describe())

DataFrame:
       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..             